config/routes.rb
Notiz::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  devise_for :users

  root 'notes#new'

  resources :notes 
  resources :note_replies, only: :index

end

app/models/note.rb
class Note < ActiveRecord::Base
	validates_presence_of :body, :recipient_email
	# validate :email_does_not_belong_to_user
	# before_create :calculate_send_date
	# before_create :delivery_date_to_send_date
	# before_create :generate_unique_ids


	belongs_to :user

# def calculate_send_date
# 	self.send_date = DateTime.now + self.days.days
# end

# def delivery_date_to_send_date
# 	self.send_date = Date.parse(self.delivery_date)
# end


# def generate_unique_ids
# 	self.reply_id = Digest::SHA256.hexdigest(body + recipient_email + sender_email + Time.now.to_s)	
# 	self.view_id = Digest::SHA256.hexdigest(body + recipient_email + sender_email + days.to_s + Time.now.to_s)
# end


def self.mail_notes
	Note.all.each do |n|
		if n.send_date == Date.today
			NotesMailer.notes_email(n.recipient_email, n.sender_email, n.body, n.days, n.view_id).deliver
		else
		end
	end
end


def self.attach_notes_to_users

	# For each note, find notes without user_id
	Note.all.each do |note|
		if !note.user
			user = User.where(:email => note.sender_email).first
			note.user = user
			note.save
		end
	end
end

# def email_does_not_belong_to_user
# 	if User.where(:email => sender_email)
# 	  self.errors[:sender_email] = "Sender email already exists"
# 	end
# end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

def new
	@note = Note.new
	 @reply_id=params[:reply_id]

  #if there is a reply id
  if params[:reply_id].present?
  #then show a flash alert
	flash[:future]= "Send a note to someone else in the future, and then your note will appear below"
  end

end


def index
 
if current_user
    @user=current_user
   	@notes=Note.order("send_date DESC").where(:user_id => @user.id).all
end


end

def show
	@note=Note.find_by(:view_id => params[:id])
	# display the note
	
	@new_note=Note.new(recipient_email: @note.sender_email)

end

def create
    # always create the note
	@user=current_user

 	if @user
 		@email = @user.email
 	else
		@email = params[:sender_email]
	end

    @note=Note.new(:body => params[:body], :recipient_email => params[:recipient_email], :sender_email => @email) 
 	
 	if @user
 	@note.user_id = @user.id
 	end

	@delivery_date = params[:delivery_date]
 	@note.send_date = Date.strptime(@delivery_date, '%m/%d/%Y')
 	
 # 	if params[:surprise_me].present?
	# 	@note.days = Random.rand(30)
	# else
		@note.days = (@note.send_date - Date.today).to_i
 # 	end


	if @note.save

	@recipient_email = params[:recipient_email]
	@days = @note.days

	flash[:success]= "Your message to #{@recipient_email} will be delivered #{@days} days in the future."

	end

# 	# check if reply id is present
# 		if params[:reply_id].present?
# 			#Find the note by reply id
# 			note=Note.find_by(:reply_id => params[:reply_id])

# 	  		# redirect to show
# 	 	 redirect_to note_path(note.view_id)
#     else
# 	  # redirect to index, show a flash message
	  redirect_to root_path
#     end
#   else
#   	render :new
#   end


 end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def after_sign_out_path_for(resource)
    root_path
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dear future</title>



    <%= stylesheet_link_tag  "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-37025398-2', 'dearfuture.me');
  ga('send', 'pageview');
</script>

</head>

<body>

<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>


  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to "HOME", root_path %></li>

    <% if current_user %>
      <li><%= link_to "SENT NOTES", notes_path %></li>
   </ul>
   
   <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to "LOGOUT", destroy_user_session_path %></li>
   </ul>    

    <% else %> 
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "LOGIN", new_user_session_path %></li>
    </ul>
    <% end %>
  </div>
</div>
     
  <% if flash[:success].present? %>
    <div class="alert-delivered">
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
      <%= flash[:success]%>
    </div>
  <% end %>

    <% if flash[:future].present? %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert"></button>
      <%= flash[:future]%>
    </div>
  <% end %>



 <%= yield %>



<!-- 
<div class="footer">
  <div class="container" align="center">
  <p>Made in Brooklyn</p>
  </div>
</div>
 -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

app/views/notes/_form.html.erb
 <div class="form-group ">



  <%= form_tag notes_path do %>


 <br>

	<%= label_tag("message")%>
	<%= text_area_tag :body, note.body, :class => "form-control"%>
	
	<%= label_tag("recipient email") %>
	<%= email_field_tag :recipient_email, note.recipient_email, :class => "form-control" %>
	
	<% unless current_user %>
		<%= label_tag("your email") %>
		<%= email_field_tag :sender_email, note.sender_email, :class => "form-control" %>
	<% end %>

	<% if note.errors.messages[:sender_email].present? %>
		<%= note.errors.messages[:sender_email].first %>
	<% end %>

	<%= label_tag("delivery date") %>
	<input class="form-control" id="delivery_date" name="delivery_date" type="text" data-provide='datepicker'>
 

<!-- 	<%= label_tag("or randomize days") %>
	<%= check_box_tag :surprise_me %>  -->


	<%= hidden_field_tag :reply_id, @reply_id %></h5>
	<%= submit_tag "SEND", :class => "btn btn-success pull-right"%>

  <% end %>

app/views/notes/index.html.erb
<div class="container">

<% if @notes.present? %>

<table class="table">
	<thead>
	 <h2>sent notes</h2>
	<tr>
		<th>created</th>
		<th>send date</th>
		<th>receipient</th>
		<th>note</th>
	</tr>
	</thead>
	<tbody>
	<% @notes.each do |n| %>
	<tr class="table">
		<td><%= n.created_at.strftime("%b %d, %Y") %></td>
		<td><%= n.send_date.strftime("%b %d, %Y")%></td>
  		<td><%= n.recipient_email %></td>
 		<td ><%= n.body %></td>
	</tr>
	<% end %>
	</tbody>
</table>

<% end %>

</div>

app/views/notes/new.html.erb
<body id="home">
<div id="hero">
<div class="container">
<div class="note">



<% if current_user %>
<% else %>
<p class="info" align="center"><%= link_to "Sign up", new_user_registration_path %> for a free account to keep track of the notes you've sent!</p>
<% end %>

<h1> dear future,</h1>
<%= render "form", note: @note %>

</div>
</div>
</div>

app/views/notes/show.html.erb
<body id="home">
<div id="hero">
<div class="container">
<div class="note">

<h3>your note from the past:</h3>

	<p><%= @note.body %></p>

<p class="pull-right"> <span class="glyphicon glyphicon-user"> </span> <%= @note.sender_email %> sent this <%= @note.days %> days ago </p>

<br>

<hr>

<h3>send a reply:</h3>
<%= render "form", note: @new_note %>

</div>
</div>
</div>